### ISSUE TITLE
[Bug] Error when player rolls for sanity triggered by GM

### ISSUE THREAD

**Issue by Vass1979** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#117]
So I trigger a sanity loss from a creature I control, targeting a player, sanity check message appears in chat, but when my player clicks on it, gets the following message: Uncaught (in promise) Error: User Cazz lacks permission to update ChatMessage CKXDpweLbym0pGwA
    at Function._onUpdate

Player has Owner permission of the actor that I am targetting

**Comment by HavlockV** [comment]
Thanks for the report. 
This happens when the actor is not the player's character.
To be able to modify the chat message the player needs to be owner of that actor AND have that actor as character. Only then can he speaks as that actor.
To be sure that your player is the owner of that actor right click on the actor in the actor directory and make sure that the player has ownership rights on that actor and save changes.
To be sure that this actor is the player's character : as a GM bring up the list of players by clicking the 'Players' menu at the bottom left of the screen. Right click on the player and select 'Player Configuration'. There you can select one of the player's owned actor and make it his impersonated character by clicking the actor below 'Select Character' to highlight it and clicking save configuration. If the actor doesn't appear on the list, it's because either the player doesn't have ownership of that character or that actor already impersonate an other player.

1) Giving ownership of actor 'harvey' to 'player 2' :
Right clik on the actor from the actor directory will bring the menu :
![image](https://user-images.githubusercontent.com/65915923/91935882-f4b38a00-ecee-11ea-85a0-026f4ca1dd65.png)
Selecting ownership right of the actor to 'player 2':
![image](https://user-images.githubusercontent.com/65915923/91935897-fed58880-ecee-11ea-838d-3001ae4307e5.png)

2) selecting 'harvey' as the character impersonating 'player 2':
Bringing up the player menu :
![image](https://user-images.githubusercontent.com/65915923/91936686-a8694980-ecf0-11ea-8173-2ed7d6d0caa7.png)
Opening the player configuration :
![image](https://user-images.githubusercontent.com/65915923/91936724-bae38300-ecf0-11ea-8e36-60fc565c5d0e.png)
Selecting the actor to impersonate and saving :
![image](https://user-images.githubusercontent.com/65915923/91936797-e1092300-ecf0-11ea-8b94-0809e87ff20e.png)

It's a design choice, to have the chat messages to be emitted as the character impersonating the player.
It can be moved to the ownership only. During testing this created some 'conflict' as an actor can be owned by different player but a player can only impersonate 1 exclusive character.
Hope this help.

**Comment by Vass1979** [comment]
Apologies, you are correct. Player had ownership of 2 characters and the wrong one was selected! Works fine!

**Comment by HavlockV** [comment]
No prob. Always appreciate to have feedback on the system.
The way foundry handles permissions, ownership, character (and tokens) is very powerful and thorough but requires a little bit of configuration and to get use to it.
Closing this now, thanks again for all the feedback.
