### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#120]
I've been working in the translation to spanish of the module (in my github account and in the FVTT official repository) and I've face some minor issues:

Text in settings is not available for translation:
https://i.ibb.co/z7CHBNS/screenshot-155.jpg
Text in background tab of the character sheet is not available for translation:
https://i.ibb.co/yBSQ2Fj/screenshot-154.jpg

The skills that require specialization does not have translation token: Firearms, Art & Craft, Science, Fighting:
https://i.ibb.co/NxBVVwL/screenshot-152.jpg

The Language skill does not allow specialization, not sure if there should be different Language skills, providing different languages or just leave people adding a new generic skill for every language other than her own.
https://i.ibb.co/hyD2gXB/screenshot-153.jpg

**Comment by Vass1979** [comment]
As far as your last point goes, Language should be two skills. Language (Own) which is equal to your EDU and then Language (Other) which should have specializations (Latin, Arabic, Greek, etc)

**Comment by lozalojo** [comment]
Yes, you are right, currently there is no Language (Other), isnt it? Then it should be added to the character sheet as an specialization skill, the problem is that it might be an open field for players to write down the language they want to specialize, instead of having a list of languages.

**Comment by HavlockV** [comment]
First of all thanks for your feedback.
> Text in settings is not available for translation:
> https://i.ibb.co/z7CHBNS/screenshot-155.jpg

Indeed, there is no translation string, it will be added in the next release. Please keep on reporting any non translated string.

> Text in background tab of the character sheet is not available for translation:
> https://i.ibb.co/yBSQ2Fj/screenshot-154.jpg

Backgrounds are  actually created dynamically and don't have predefined names.
You can remove, reorder or create new entries on the fly.
To do so you need first to unlock the sheet by clicking the lock on the top right corner :
![image](https://user-images.githubusercontent.com/65915923/92272896-b71b5080-eeea-11ea-96ea-55232ff25680.png)
Once the sheet is unlocked you can create, edit, reorder, rename or reorder any element.
![image](https://user-images.githubusercontent.com/65915923/92272978-d3b78880-eeea-11ea-82f3-3424106f17cb.png)
![image](https://user-images.githubusercontent.com/65915923/92272991-d9ad6980-eeea-11ea-81a5-9f559f5a0396.png)
![image](https://user-images.githubusercontent.com/65915923/92272995-ddd98700-eeea-11ea-88fa-243eab1d9b59.png)

> The skills that require specialization does not have translation token: Firearms, Art & Craft, Science, Fighting:
> https://i.ibb.co/NxBVVwL/screenshot-152.jpg

Skills specializations have free names. You can rename any skill specialization. To create a new specialization just flag the skill as a specialization and fill the corresponding field. You can change the name of an existing specialization just by editing it.
![image](https://user-images.githubusercontent.com/65915923/92273545-d797da80-eeeb-11ea-9678-7d5a70589d10.png)
Some specializations (Firearms and Fighting) have predetermined name that you can localize. The reason being that those skills are used by the combat flow system. Here are the corresponding strings :
![image](https://user-images.githubusercontent.com/65915923/92273638-06ae4c00-eeec-11ea-97e0-963e841dfabd.png)

> The Language skill does not allow specialization, not sure if there should be different Language skills, providing different languages or just leave people adding a new generic skill for every language other than her own.
> https://i.ibb.co/hyD2gXB/screenshot-153.jpg

You can create any language skill just by typing 'language' in the specialization field.
Unlock the sheet, click on the add skill button and fill the popup window.
![image](https://user-images.githubusercontent.com/65915923/92274071-dc10c300-eeec-11ea-9cab-0407393061f1.png)
![image](https://user-images.githubusercontent.com/65915923/92274095-e29f3a80-eeec-11ea-9e54-859020b647e9.png)
![image](https://user-images.githubusercontent.com/65915923/92274109-e6cb5800-eeec-11ea-9eff-8e01fd776f61.png)


The skill system was design to accommodate as many skills as possible. There are in CoC as many skills as there are keepers, and many keepers (including me) are creating our own skills. In one of my recent game I had my PC trying to convince a jury.
I gave them each a corresponding skill : 'commiserate the jury' :
![image](https://user-images.githubusercontent.com/65915923/92274581-cd76db80-eeed-11ea-92b2-8aa52a37adcc.png)
Depending on their argument/speech I was that score (Non of them was hung in the end, but that's a different story)
Therefore  skills are actually items that you can create and drag and drop on any PC/NPC/Creature. This is to give as much flexibility as possible. That's again a design choice. It's not fully satisfactory and his on the 'to improve' list (specialization especially).
I realize that I should probably write a short wiki or tutorial, that's on the very long TODO list.

You should create for your language a compendium including all the skills you need to start a PC and a corresponding sheet with your background section. That's what I did for my games in french. Distributing those compendium will probably fall under the copyright restriction. The skill compendium and the PC sheet given as example are just .... well examples. 
Here is what my french compendium looks like:

![image](https://user-images.githubusercontent.com/65915923/92275374-4dea0c00-eeef-11ea-914b-329950fcdcb7.png)
and a skill example :
![image](https://user-images.githubusercontent.com/65915923/92275399-56424700-eeef-11ea-9e01-a7dc2b3d86e4.png)

Due to copyright restrictions I can't unfortunately provide any compendium for skill, weapons, spells etc...

**Comment by lozalojo** [comment]
Hi, HavlockV.

Sorry if I have not enought knowledge of the module to make the right questions, i'm learning little by little.

Backgrounds: I thought there was something configurable in the "1920 Character" template of the CoC7.examples.json, when I create a new pc using the template, the background fields are created automatically, so there might be something somewhere that tells the sheet to have those values. If it cant be translated, I'd leave the background tab empty.

Skills specialization: If you take a look at es.json those skills are already translated:
![](https://i.ibb.co/Q9h70zM/screenshot-161.jpg)
But it does not appear in the character sheet, I've also translated in the "1920 Character" template of the CoC7.examples.json.
![](https://i.ibb.co/VCY6CJ8/screenshot-160.jpg)

**Comment by HavlockV** [comment]
> Sorry if I have not enought knowledge of the module to make the right questions, i'm learning little by little.

No reason to be sorry. CoC is a very open system and has very loose rules. Choices have been made to try to cover as much as possibles. When I started this last June I had zero experience with either javascript/html or css, so choices made might not have been the best solutions. It will change as I gain experience, always trying to keep a backward compat.

> Backgrounds: I thought there was something configurable in the "1920 Character" template of the CoC7.examples.json, when I create a new pc using the template, the background fields are created automatically, so there might be something somewhere that tells the sheet to have those values. If it cant be translated, I'd leave the background tab empty.

The 1920 Character is an example of what to do. This shouldn't be used unless you want to play in English. A lot of things in that sheet are hard-coded in English (Skills, Background section names...). French keepers that are using the system created their own compendium with french skills and character sheets.

> Skills specialization: If you take a look at es.json those skills are already translated:
That's indeed a bug, it will be corrected on the next release. Thanks for your feedback.

**Comment by Vass1979** [comment]
> When I started this last June I had zero experience with either javascript/html or css, so choices made might not have been the best solutions. It will change as I gain experience, always trying to keep a backward compat.

That gives me hope I gotta say to try and learn! Only knowledge I have is from PHP like a decade ago!

**Comment by lozalojo** [comment]
Great, I'll keep an eye in the development for those bug fixes to improve the translation module.

Thanks!

**Comment by lozalojo** [comment]
I've seen specializations have been fixed, thanks!

If I understand right, specializations that are used in the mechanics, like Firearms and Fighting, can be translated using their own token in the es.json file, but the rest of specializations are locale specific, and so must be created for each game, and the default  english skills compendium only support english names, isnt it?

![](https://i.ibb.co/5c8tzmy/screenshot-164.jpg)

**Comment by HavlockV** [comment]
First of all a warning. If you translated the thing contained in the compendiums directly they will be overwritten at every release. You have to get your translated sheet(s)/Skills/items in separates compendiums or keep them in your actors/items directory.
For the combat skills the specialization is added by the system. For all others specializations the name has to be entered manually and is not localized. You can edit the skills from the sheet and change the specialization name in the skill sheet.
There's a module called Babele that allows for compendium translation but I'm not familiar with how it works.
What could easily be done is to create compendiums for your language one for the translated sheet(s) and one for the skills.
If you provide me with those compendium I will happily include them in the system, providing they don't have any copyrighted text from the books.
Creating compendiums in the system needs to be done manually, if you don't know how to do that, just create the compendium in your world and send me the .db files located in the world you created (FoundryVTT\Data\worlds\WORLD_NAME\packs)
Ideally those compendiums should be distributed as modules.

**Comment by lozalojo** [comment]
HavlockV, my translation module is already for Babele:

![call-of-cthulhu-7th-babele-es](https://github.com/lozalojo/call-of-cthulhu-7th-babele-es)

So the files I use (the ones at the github) are independent from the system (CoC7) files, I only have to track the changes in the compendiums and es.json file and translate them.

I have an updated es.json file in my module, From now on, I will make a pull request to your project from time to time, for you to have es.json updated.

**Comment by HavlockV** [comment]
I'll have a look at it when I find some time (after finishing comabt flows probably)
Thank for the feedback, I leave this open as a reminder.
