### ISSUE TITLE
[Bug] Skills associated to weapons

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#173]
I create an Occupation with skill Fighting (Brawl).
If I add the Punch weapon (which uses Fighting (Brawl)) to the occupation, when creating the PC, the process ask me for the skill associated with Punch and allows me to enter again Brawl/Fighting, but base is 0.

I think it creates the skill as if it were new instead of using the one in the Skills compendium, I know it because I use icons for skills, and all the skills has the appropiate icon except the newly created Fighting (Brawl), which has the generic icon.

So better off without adding default weapons (in fact I only add "Unarmed" weapon).

Does this make sense to the process of adding skills to the character sheet?

**Comment by HavlockV** [comment]
When adding a weapon it tries to find a skill based on the name without the specialization. In that example the skill in the Weapon sheet should be named Brawl. If you name it Fighting (Brawl) it will not recognize it. After it is looking for skills in the character sheet not in the compendium.
I'll make the skill searching more aggressive, looking for closest match instead of exact match in the sheet first, then in compendium and if nothing found create a new one.
Items can be included in Setup, you can add the unarmed 'weapon' in it.

**Comment by lozalojo** [comment]
Yes, that's what I've done. I have Unarmed created as a weapon in my weapon's compendium, its the way it should be handled, imho.

**Comment by HavlockV** [comment]
weapons were created before skills.... hence, he couldn't find the skill for that weapon as it wasn't created yet.
It should be OK now, plus retrieving of the skill associated with a weapon has been hardened and is more aggressive.
