### ISSUE TITLE
Creature/NPC sheet

### ISSUE THREAD

**Issue by HavlockV** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#193]
On creature sheets, when the spell list exceed the sheet size, there's no slider to scroll down the list.

**Comment by kckaiwei** [comment]
This can likely be fixed by removing  ` overflow-y: hidden;`  from coc7.css:589, since it would be in the interest of making everything scrollable. 

However, that introduces the problem where clicking on a character sheet will open it up. But once you expand inventory, and drag the window, it'll lock into maximized mode.  The drag hook for windows will probably need to be examined as well here. More research is probably needed.

Also, how does the `.less` files work here. Do you have a compile script? I don't see a `package.json` for node_modules, so I assume you just installed gulp globally, and use it just for these `.less` files?
