### ISSUE TITLE
Possible bugs after update to 7.5??

### ISSUE THREAD

**Issue by Mcgarnagle1** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#204]
Not sure if these are bugs after I updated to Foundry 7.5, but I've noticed a couple things that aren't working right for me anymore.

1. The gears that allow us to edit items on the character sheet is now gone. I can't seem to add or remove skills (unless I drag them from the compendium), add background items, etc. I see that you added a development and character creation toggle for the GM to use (brilliant, by the way). Not sure you created another way to edit the sheet with that update?

2. The dice so nice app animates if I'm using the module "dice tray" but it seems to not animate any dice when I click on a rollable item from a character sheet or NPC card. The results do show up in the chat, just no animated dice.

**Comment by RavenknightDM** [comment]
0.7.5 oddities. Not sure if they are related to the latest version of CoC or Foundry since I updated them at the same time. (Smart!)

The padlock and gears are gone for characters but still there for creatures.

I'm having problem getting the attack macros to function. None of the old characters in my game can attack using the weapons and macros created with CoC 0.3.8 and new characters can attack only as long as they have no targets selected. These broken macros will not start or show up in the chat at all.

Edit:
Made some more tests. 

A new character works fine as long as I don't target another character when performing an attack macro. If I select a target then the new character will break for me as well. None of my old characters can perform attacks but other skills works just fine.

Re-Edit:
All works fine with 4.0! :)

**Comment by HavlockV** [comment]
Hi, I'm sorry I missed this.
this should have been corrected with the first '0.7.x' compatible version.
I'll close that issue for now, please feel free to reopen it if you are still encountering some problems.
