### ISSUE TITLE
[Bug] Inventory panel continously collapsing in creature/NPC templates

### ISSUE THREAD

**Issue by sharcashmo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#222]
Inventory panel is continuously collapsing in creature/NPC templates, even when it has data inside

**Comment by HavlockV** [comment]
There's indeed some weird comportment there. I managed to reproduce it.
It stops when you move the sheet. I'll have a look at it.
Thanks for report, appreciated.

**Comment by kckaiwei** [comment]
Is this fixed? Not sure what the original bug is. 

I see that if I have a npc/creature has an item in it's inventory, the inventory tab will be collapsed when selecting it. If you close the sheet and reopen it, it'll be closed again, instead of open by default. Is that what we're looking to do? I added a PR to have it shown as open as default, since that seems like the better behavior for a keeper that's juggling multiple creatures.

**Comment by HavlockV** [comment]
@kckaiwei Thanks for your help, this will be published with the next release.
