### ISSUE TITLE
[Bug][Dev] Death icon

### ISSUE THREAD

**Issue by lozalojo** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#293]
To be consistent with the rest of character states, the non-clicked and clicked version of "death" might be the same, isnt it? The difference might be if it is on (stroke icon) or off (non-stroke icon)

On:
![](https://i.ibb.co/Yk56d86/screenshot-5.jpg)
Off (different icon):
![](https://i.ibb.co/zxSLjqy/screenshot-6.jpg)

**Comment by HavlockV** [comment]
The dice Icon is the last step before actual death (the CON check).
I may highlight it differently or put both icons.

**Comment by lozalojo** [comment]
Ops, I didnt notice that, but it is not already covered by "dying" icon? (when you have to roll for CON each turn?), or does the dice icon allows to roll for CON when dying?

**Comment by HavlockV** [comment]
How it is coded (it's not fixed, just reproduced from previous sheet):
If you click on dying this will only activate/deactivate the dying status.
If you have dying active this will activate (you can click it) the dice icon which otherwise is inactive (clicking/hovering it will do nothing).
Then you can click that icon (with or without shift to  fast forward) this will trigger the roll, if you fail death status will occur.
Only GM can activate/deactivate status.
Player can only click the dice when dying status is active.

**Comment by lozalojo** [comment]
Then I think it is fine, isnt it?
