### ISSUE TITLE
Translation of character sheets into French

### ISSUE THREAD

**Issue by keldrilh** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#406]
Hello,
how can the files be translated into French? Is there a properties file for this? Otherwise I am ready to send you all the skills translation if you wish.
Congratulations again for all this work..

**Comment by keldrilh** [comment]
OK, I saw the translation files. On the other hand, by changing the language to French, the file is not updated.

**Comment by lozalojo** [comment]
The system is already translated to french, you only have to install the Translation: French [Core] module and set your Foundry server language preferences to French, and change your world language to french.

**Comment by HavlockV** [comment]
Hi Keldrilh. Thanks for your feedback.
As usual Lozalojo is right, this should work in french.
Please let us know if you managed to change your language.
N'hesite pas a venir faire un tour sur le discord Foundry FR : La Fonderie

**Comment by keldrilh** [comment]
Hello and thank you for your feedback :)
I think I have configured everything in French and you will see that on the screenshot of the example sheet, the skills remain in English. In addition I have error messages that appear which you see on the screen.
![FoudryVTT screen 4](https://user-images.githubusercontent.com/57942337/110513176-3b52c880-8106-11eb-8b3a-f0462916e6d2.png)
![FoudryVTT screen 1](https://user-images.githubusercontent.com/57942337/110513178-3beb5f00-8106-11eb-9a1e-78a8e0dc5f8d.png)
![FoudryVTT screen 2](https://user-images.githubusercontent.com/57942337/110513180-3c83f580-8106-11eb-8b37-4132026e4a0d.png)
![FoudryVTT screen 3](https://user-images.githubusercontent.com/57942337/110513182-3c83f580-8106-11eb-927f-aeba882cc3a4.png)

**Comment by lozalojo** [comment]
Ops, I see, there is a problem of concept, what it is translated is the Core Foundry and CoC/Havlock system, but you have to create your own compendia to use in your games, the skills in the CoC system are there as a reference, and they are in english.

When you create your set of skills you will enter in french, then you will create a setup for the era you play and add your skills, and finally create an occupation and add the linked skills to it, then, with your custom setup and occupation, you'll newly created characters will be fully in french.

I recommend you to create the framework (skills, setups, occupations) and then create a module, so that when you load that module you'll have all the content for all your games.
