### ISSUE TITLE
[new function] San Check by Commond

### ISSUE THREAD

**Issue by zeteticl** [Miskatonic-Investigative-Society/CoC7-FoundryVTT#469]
San Check by Commond 
It can read the san on character sheet, and auto reduce the san
Example:
/sc 1/2d3
/sc 1/1d10+1

https://github.com/hktrpg/FVTT-coc7th-SC/blob/main/index.js

Line 1 to line 150

**Comment by HavlockV** [comment]
Hi zeteticl,
Great job and the chat command is a nice addition.
There's already something like that built in the system by alt+click on the Sanity in the sheet, but I will gladly push this update.
Just something regarding the phobia/mania tables that are built in your code. That may be considered copyrighted material and may bring some issues with Chaosium. So I can't really release it like this.
But ! there is already in the system a space for those tables. They are called Bout of Madness (Summary/Real Time) and are defined in the settings.
They come empty again because of the copyright issue, but any user can fill them for his system.
You can retrieve those table using :
`const boutOfMadnessTableId = game.settings.get( 'CoC7', 'boutOfMadnessRealTimeTable')` or `game.settings.get( 'CoC7', 'boutOfMadnessSummaryTable')`
then
`const boutOfMadnessTable = game.tables.get( boutOfMadnessTableId);`
and roll them using :
`result.tableRoll = boutOfMadnessTable.roll();`
This will be recursive and will continue until something is found.
You have an example in actor.js line 180.
Could you just make a pull request to have this directly integrated, and I will pass it with the next iteration.
Thanks for your participation !!
